# Preprocessing Phase

In [1]:
import nltk

nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /Users/victor/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/victor/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/victor/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/victor/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /Users/victor/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]

True

In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import string as st
import re
from nltk import PorterStemmer, WordNetLemmatizer

# Input data files are available in the read-only "./input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('./input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
# Read the data. Here it is already in .csv format.
train_data = pd.read_csv('dataset/BBC News Train.csv')
test_data = pd.read_csv('dataset/BBC News Test.csv')
data = pd.concat([train_data,test_data])
data.to_csv('dataset/data.csv', index=False)
data.head(10)

ArticleId                                               Text       Category
0       1833  worldcom ex-boss launches defence lawyers defe...       business
1        154  german business confidence slides german busin...       business
2       1101  bbc poll indicates economic gloom citizens in ...       business
3       1976  lifestyle  governs mobile choice  faster  bett...           tech
4        917  enron bosses in $168m payout eighteen former e...       business
5       1582  howard  truanted to play snooker  conservative...       politics
6        651  wales silent on grand slam talk rhys williams ...          sport
7       1797  french honour for director parker british film...  entertainment
8       2034  car giant hit by mercedes slump a slump in pro...       business
9       1866  fockers fuel festive film chart comedy meet th...  entertainment

In [4]:
data.shape

(2225, 3)

# Text cleaning and processing steps
* Remove punctuations
* Convert text to tokens
* Remove tokens of length less than or equal to 3
* Remove stopwords using NLTK corpus stopwords list to match
* Apply stemming
* Apply lemmatization
* Convert words to feature vectors

In [5]:
# Remove all punctuations from the text

def remove_punct(text):
    return ("".join([ch for ch in text if ch not in st.punctuation]))

In [6]:
data['removed_punc'] = data['Text'].apply(lambda x: remove_punct(x))
data.head()

ArticleId                                               Text  Category  \
0       1833  worldcom ex-boss launches defence lawyers defe...  business   
1        154  german business confidence slides german busin...  business   
2       1101  bbc poll indicates economic gloom citizens in ...  business   
3       1976  lifestyle  governs mobile choice  faster  bett...      tech   
4        917  enron bosses in $168m payout eighteen former e...  business   

                                        removed_punc  
0  worldcom exboss launches defence lawyers defen...  
1  german business confidence slides german busin...  
2  bbc poll indicates economic gloom citizens in ...  
3  lifestyle  governs mobile choice  faster  bett...  
4  enron bosses in 168m payout eighteen former en...

In [7]:
''' Convert text to lower case tokens. Here, split() is applied on white-spaces. But, it could be applied
    on special characters, tabs or any other string based on which text is to be seperated into tokens.
'''
def tokenize(text):
    text = re.split('\s+' ,text)
    return [x.lower() for x in text]

In [8]:
data['tokens'] = data['removed_punc'].apply(lambda msg : tokenize(msg))
data.head()

ArticleId                                               Text  Category  \
0       1833  worldcom ex-boss launches defence lawyers defe...  business   
1        154  german business confidence slides german busin...  business   
2       1101  bbc poll indicates economic gloom citizens in ...  business   
3       1976  lifestyle  governs mobile choice  faster  bett...      tech   
4        917  enron bosses in $168m payout eighteen former e...  business   

                                        removed_punc  \
0  worldcom exboss launches defence lawyers defen...   
1  german business confidence slides german busin...   
2  bbc poll indicates economic gloom citizens in ...   
3  lifestyle  governs mobile choice  faster  bett...   
4  enron bosses in 168m payout eighteen former en...   

                                              tokens  
0  [worldcom, exboss, launches, defence, lawyers,...  
1  [german, business, confidence, slides, german,...  
2  [bbc, poll, indicates, economic, gloom, citize...  
3  [lifestyle, governs, mobile, choice, faster, b...  
4  [enron, bosses, in, 168m, payout, eighteen, fo...

In [9]:
# Remove tokens of length less than 3

def remove_small_words(text):
    return [x for x in text if len(x) > 3 ]

In [10]:
data['larger_tokens'] = data['tokens'].apply(lambda x : remove_small_words(x))
data.head()

ArticleId                                               Text  Category  \
0       1833  worldcom ex-boss launches defence lawyers defe...  business   
1        154  german business confidence slides german busin...  business   
2       1101  bbc poll indicates economic gloom citizens in ...  business   
3       1976  lifestyle  governs mobile choice  faster  bett...      tech   
4        917  enron bosses in $168m payout eighteen former e...  business   

                                        removed_punc  \
0  worldcom exboss launches defence lawyers defen...   
1  german business confidence slides german busin...   
2  bbc poll indicates economic gloom citizens in ...   
3  lifestyle  governs mobile choice  faster  bett...   
4  enron bosses in 168m payout eighteen former en...   

                                              tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [bbc, poll, indicates, economic, gloom, citize...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, in, 168m, payout, eighteen, fo...   

                                       larger_tokens  
0  [worldcom, exboss, launches, defence, lawyers,...  
1  [german, business, confidence, slides, german,...  
2  [poll, indicates, economic, gloom, citizens, m...  
3  [lifestyle, governs, mobile, choice, faster, b...  
4  [enron, bosses, 168m, payout, eighteen, former...

In [11]:
''' Remove stopwords. Here, NLTK corpus list is used for a match. However, a customized user-defined 
    list could be created and used to limit the matches in input text. 
'''
def remove_stopwords(text):
    return [word for word in text if word not in nltk.corpus.stopwords.words('english')]

In [12]:
data['clean_tokens'] = data['larger_tokens'].apply(lambda x : remove_stopwords(x))
data.head()

ArticleId                                               Text  Category  \
0       1833  worldcom ex-boss launches defence lawyers defe...  business   
1        154  german business confidence slides german busin...  business   
2       1101  bbc poll indicates economic gloom citizens in ...  business   
3       1976  lifestyle  governs mobile choice  faster  bett...      tech   
4        917  enron bosses in $168m payout eighteen former e...  business   

                                        removed_punc  \
0  worldcom exboss launches defence lawyers defen...   
1  german business confidence slides german busin...   
2  bbc poll indicates economic gloom citizens in ...   
3  lifestyle  governs mobile choice  faster  bett...   
4  enron bosses in 168m payout eighteen former en...   

                                              tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [bbc, poll, indicates, economic, gloom, citize...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, in, 168m, payout, eighteen, fo...   

                                       larger_tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [poll, indicates, economic, gloom, citizens, m...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, 168m, payout, eighteen, former...   

                                        clean_tokens  
0  [worldcom, exboss, launches, defence, lawyers,...  
1  [german, business, confidence, slides, german,...  
2  [poll, indicates, economic, gloom, citizens, m...  
3  [lifestyle, governs, mobile, choice, faster, b...  
4  [enron, bosses, 168m, payout, eighteen, former...

### Lemmatization converts word to it's dictionary base form. This process takes language grammar and vocabulary into consideration while conversion. Hence, it is different from Stemming in that it does not merely truncate the suffixes to get the root word.


In [13]:
# Apply lemmatization on tokens
def lemmatize(text):
    word_net = WordNetLemmatizer()
    return [word_net.lemmatize(word) for word in text]

In [14]:
data['lemma_words'] = data['clean_tokens'].apply(lambda x : lemmatize(x))
data.head()

ArticleId                                               Text  Category  \
0       1833  worldcom ex-boss launches defence lawyers defe...  business   
1        154  german business confidence slides german busin...  business   
2       1101  bbc poll indicates economic gloom citizens in ...  business   
3       1976  lifestyle  governs mobile choice  faster  bett...      tech   
4        917  enron bosses in $168m payout eighteen former e...  business   

                                        removed_punc  \
0  worldcom exboss launches defence lawyers defen...   
1  german business confidence slides german busin...   
2  bbc poll indicates economic gloom citizens in ...   
3  lifestyle  governs mobile choice  faster  bett...   
4  enron bosses in 168m payout eighteen former en...   

                                              tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [bbc, poll, indicates, economic, gloom, citize...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, in, 168m, payout, eighteen, fo...   

                                       larger_tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [poll, indicates, economic, gloom, citizens, m...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, 168m, payout, eighteen, former...   

                                        clean_tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [poll, indicates, economic, gloom, citizens, m...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, 168m, payout, eighteen, former...   

                                         lemma_words  
0  [worldcom, exboss, launch, defence, lawyer, de...  
1  [german, business, confidence, slide, german, ...  
2  [poll, indicates, economic, gloom, citizen, ma...  
3  [lifestyle, governs, mobile, choice, faster, b...  
4  [enron, boss, 168m, payout, eighteen, former, ...

In [15]:
# Create sentences to get clean text as input for vectors

def return_sentences(tokens):
    return " ".join([word for word in tokens])

In [16]:
data['clean_text'] = data['lemma_words'].apply(lambda x : return_sentences(x))
data.head()


ArticleId                                               Text  Category  \
0       1833  worldcom ex-boss launches defence lawyers defe...  business   
1        154  german business confidence slides german busin...  business   
2       1101  bbc poll indicates economic gloom citizens in ...  business   
3       1976  lifestyle  governs mobile choice  faster  bett...      tech   
4        917  enron bosses in $168m payout eighteen former e...  business   

                                        removed_punc  \
0  worldcom exboss launches defence lawyers defen...   
1  german business confidence slides german busin...   
2  bbc poll indicates economic gloom citizens in ...   
3  lifestyle  governs mobile choice  faster  bett...   
4  enron bosses in 168m payout eighteen former en...   

                                              tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [bbc, poll, indicates, economic, gloom, citize...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, in, 168m, payout, eighteen, fo...   

                                       larger_tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [poll, indicates, economic, gloom, citizens, m...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, 168m, payout, eighteen, former...   

                                        clean_tokens  \
0  [worldcom, exboss, launches, defence, lawyers,...   
1  [german, business, confidence, slides, german,...   
2  [poll, indicates, economic, gloom, citizens, m...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, bosses, 168m, payout, eighteen, former...   

                                         lemma_words  \
0  [worldcom, exboss, launch, defence, lawyer, de...   
1  [german, business, confidence, slide, german, ...   
2  [poll, indicates, economic, gloom, citizen, ma...   
3  [lifestyle, governs, mobile, choice, faster, b...   
4  [enron, boss, 168m, payout, eighteen, former, ...   

                                          clean_text  
0  worldcom exboss launch defence lawyer defendin...  
1  german business confidence slide german busine...  
2  poll indicates economic gloom citizen majority...  
3  lifestyle governs mobile choice faster better ...  
4  enron boss 168m payout eighteen former enron d...

# Model and Evaluation Phase

In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [18]:
X_train, X_test, y_train, y_test = train_test_split(data['clean_text'], data['Category'], test_size=0.2, random_state=42)

In [19]:
#vectorizer = CountVectorizer()
#X_train_vec = vectorizer.fit_transform(X_train)
#X_test_vec = vectorizer.transform(X_test)

# OR

vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [20]:
def train_and_evaluate(classifier, X_train_vec, y_train, X_test_vec, y_test):
    classifier.fit(X_train_vec, y_train)
    y_pred = classifier.predict(X_test_vec)
    accuracy = accuracy_score(y_test, y_pred)
    classification_report_dict = classification_report(y_test, y_pred, output_dict=True)
    
    print(classifier.__class__.__name__)
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("\n")
    
    performance = {
        "accuracy": accuracy,
        "precision": classification_report_dict["macro avg"]["precision"],
        "recall": classification_report_dict["macro avg"]["recall"],
        "f1_score": classification_report_dict["macro avg"]["f1-score"],
    }
    
    return performance

In [21]:
performance_metrics = {}

classifiers = [
    MultinomialNB(),
    LogisticRegression(),
    LinearSVC(),
    RandomForestClassifier(),
    KNeighborsClassifier()
]

for classifier in classifiers:
    performance_metrics[classifier.__class__.__name__] = train_and_evaluate(classifier, X_train_vec, y_train, X_test_vec, y_test)


MultinomialNB
Accuracy: 0.7280898876404495
Classification Report:
                precision    recall  f1-score   support

     business       0.72      0.75      0.73        92
entertainment       0.74      0.67      0.71        82
     politics       0.73      0.73      0.73        83
        sport       0.71      0.79      0.75       101
         tech       0.75      0.68      0.71        87

     accuracy                           0.73       445
    macro avg       0.73      0.73      0.73       445
 weighted avg       0.73      0.73      0.73       445

Confusion Matrix:
 [[69  4  4 10  5]
 [ 8 55  6  8  5]
 [ 3  7 61  8  4]
 [ 8  3  4 80  6]
 [ 8  5  9  6 59]]


LogisticRegression
Accuracy: 0.7303370786516854
Classification Report:
                precision    recall  f1-score   support

     business       0.70      0.74      0.72        92
entertainment       0.74      0.71      0.72        82
     politics       0.73      0.73      0.73        83
        sport       0.72      

In [22]:
for classifier, metrics in performance_metrics.items():
    print(f"{classifier}:")
    for metric, value in metrics.items():
        print(f"  {metric}: {value:.4f}")
    print("\n")


MultinomialNB:
  accuracy: 0.7281
  precision: 0.7299
  recall: 0.7252
  f1_score: 0.7263


LogisticRegression:
  accuracy: 0.7303
  precision: 0.7328
  recall: 0.7283
  f1_score: 0.7296


LinearSVC:
  accuracy: 0.6944
  precision: 0.6966
  recall: 0.6918
  f1_score: 0.6928


RandomForestClassifier:
  accuracy: 0.7034
  precision: 0.7077
  recall: 0.6998
  f1_score: 0.7017


KNeighborsClassifier:
  accuracy: 0.6697
  precision: 0.6712
  recall: 0.6666
  f1_score: 0.6670


